name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Produce output
      run: python find_lowest_number.py numbers.txt output1.txt  > output1.txt
    - name: test1
      run: diff expected1.txt output1.txt
