name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Produce output for test 1
      run: python find_lowest_number.py numbers/numbers1.txt output1.txt  > output1.txt
    - name: Produce output for test 2
      run: python find_lowest_number.py numbers/numbers2.txt output2.txt  > output2.txt
    - name: Produce output for test 3
      run: python find_lowest_number.py numbers/numbers3.txt output3.txt  > output3.txt
      
    - name: test1
      run: diff test_data/expected1.txt output1.txt
    - name: test2
      run: diff test_data/expected2.txt output2.txt
    - name: test3
      run: diff test_data/expected3.txt output3.txt
